export const USER_ROLES = {
  ADMIN: 'ADMIN',
  EMPLOYEE: 'EMPLOYEE'
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  LATE: 'LATE',
  ABSENT: 'ABSENT',
  ON_LEAVE: 'ON_LEAVE',
  HALF_DAY: 'HALF_DAY'
};

export const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const REMARK_CATEGORIES = {
  PRAISE: 'PRAISE',
  IMPROVEMENT: 'IMPROVEMENT',
  GOAL: 'GOAL',
  GENERAL: 'GENERAL'
};
